### ISSUE TITLE
Mod the Spire 3.6.3 compatibility? 

### ISSUE THREAD

**Issue by AvangionQ** [lobbienjonsji/StuffTheSpire#2]
I want to try this, but I'm using Mod the Spire 3.6.3 and this release requires 3.8.0 ... any chance for some backward compatibility?

**Comment by lobbienjonsji** [comment]
There should be no issues with older mod the spire versions so probably I can do that.

**Comment by AvangionQ** [comment]
Something to look forward to then ... post a reply here when it's up and I'll give it a try ... no rush ... 😺
