### ISSUE TITLE
Crash when accepting the Horseman event reward

### ISSUE THREAD

**Issue by blahthebiste** [lobbienjonsji/StuffTheSpire#3]
Heavily modded game, Act 2 i encountered the Horseman event. It was all good until the final phase, where the only choice is take 10 damage and receive a special blessing (iirc). Game crashed upon clicking that.

Here's the log:
[crashlog.txt](https://github.com/lobbienjonsji/StuffTheSpire/files/3353400/crashlog.txt)

**Comment by lobbienjonsji** [comment]
Fixed in the newest update.

**Comment by blahthebiste** [comment]
Awesome, thanks! I'll try it out right away.
