### ISSUE TITLE
Silent's "Final Struggle" healing one less stack of HP than it should when it kills the last enemy in a combat.

### ISSUE THREAD

**Issue by goldencow2** [lobbienjonsji/StuffTheSpire#7]
![Untitled](https://user-images.githubusercontent.com/43799724/74687849-3ccbee80-519b-11ea-8f47-f754cb57e5df.png)

If combat ends because Struggle kills the last enemy, I end up 5 HP short. It works properly if there are more enemies left.

_(as an aside the vanilla game capitalizes it as "HP" and I think it should be "lose" not "loose")_

**Comment by lobbien** [comment]
Ok, will fix, thank you for the report!

**Comment by lobbien** [comment]
And done!
